### ISSUE TITLE
Dashboard doesn't work for me

### ISSUE THREAD

**Issue by vassyz** [pda/flip#35]
I'm on Rails 4.2.2. The dashboard is just a blank page.
And I don't really understand how features get added to the database.

**Comment by mfazekas** [comment]
I think it's same as https://github.com/pda/flip/issues/1

For me adding an initializer/flip.rb with 
```ruby
Feature
```
to make sure features are loaded did fix it.

**Comment by j1mmie** [comment]
This fixed it for me as well
