### ISSUE TITLE
Flip::Cacheable is not included in the gem

### ISSUE THREAD

**Issue by dfurber** [pda/flip#40]
Looks like that feature got added since 1.0.1 came out. Care to push out a version 1.0.2 please?

**Comment by ishields** [comment]
Hello!  Is there anyway we can get the 1.0.2 release made so that people can use Flip::Cacheable?  It shows in the readme so I'm guessing people try to use it and can't.  Thanks!

**Comment by dannycodes** [comment]
The Gem has been updated to 1.1.0

**Comment by dannycodes** [comment]
@pda Can close this issue
