### ISSUE TITLE
ActiveSupport conflict causes Bundler to fail on Rails 5.0

### ISSUE THREAD

**Issue by stevepaulo** [pda/flip#42]
Flip requires activesupport-4.2.6, and rails-5.0.0 requires activesupport-5.0.0, so Bundler chokes on the dependency requirements.

Is there a known issue with activesupport-5.0.0 that Flip can't work out of the box with that version?

**Comment by stevepaulo** [comment]
Actually, it looks like the code was added to support the newest activesupport, but a new version was never pushed to RubyGems...

**Comment by pda** [comment]
→ https://github.com/pda/flip/pull/41#issuecomment-231135711
